version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: applongpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    env_file: .env.example
    environment:
      DATABASE_URL: postgresql+psycopg2://appuser:applongpass@db:5432/stockdb
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./exports:/app/exports

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
